#
# © 2021 TomTom NV. All rights reserved.
#
# This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
# used for internal evaluation purposes or commercial use strictly subject to separate
# license agreement between you and TomTom NV. If you are the licensee, you are only permitted
# to use this software in accordance with the terms of your license agreement. If you are
# not the licensee, you are not authorized to use this software in any manner and should
# immediately return or destroy it.
#

# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  main-release:
    type: maven-repository
    url: https://repositories.tomtom.com/artifactory/sdk-maven
    username: ${{secrets.ARTIFACTORY_USERNAME}}
    password: ${{secrets.ARTIFACTORY_PASSWORD}}
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - main-release
    schedule:
      interval: "daily"
      # Check for updates at 2am UTC
      time: "02:00"
    open-pull-requests-limit: 10
    reviewers:
      - "joserojas-tomtom"
      - "AdrianGlasnapp-TomTom"
      - "ioanakanda-tomtom"
      - "LukaszWitkowski-tomtom"
