name: Android Build

on: push

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:

      - name: Checkout
        uses: actions/checkout@v2
      - name: SETUP JVM 17
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 17
      - name: Print JVM version
        run: javac -version
      - name: Wrapper permissions
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew assemble -PrepositoryUsername=${{secrets.ARTIFACTORY_USERNAME}} -PrepositoryIdentityToken=${{secrets.ARTIFACTORY_PASSWORD}} -PtomtomApiKey=${{secrets.TOMTOM_API_KEY}}
